In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Data processing
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
ratings=pd.read_csv('/content/drive/Shareddrives/rs assignment1/interactions_train.csv')
# Take a look at the data
ratings.head()


user_id  recipe_id        date  rating      u       i
0     2046       4684  2000-02-25     5.0  22095   44367
1     2046        517  2000-02-25     5.0  22095   87844
2     1773       7435  2000-03-13     5.0  24732  138181
3     1773        278  2000-03-13     4.0  24732   93054
4     2046       3431  2000-04-07     5.0  22095  101723

In [ ]:
# Read in data
recipes = pd.read_csv('/content/drive/Shareddrives/rs assignment1/RAW_recipes.csv')
# Take a look at the data
recipes.head()

name      id  minutes  \
0  arriba   baked winter squash mexican style  137739       55   
1            a bit different  breakfast pizza   31490       30   
2                   all in the kitchen  chili  112140      130   
3                          alouette  potatoes   59389       45   
4          amish  tomato ketchup  for canning   44061      190   

   contributor_id   submitted  \
0           47892  2005-09-16   
1           26278  2002-06-17   
2          196586  2005-02-25   
3           68585  2003-04-14   
4           41706  2002-10-25   

                                                tags  \
0  ['60-minutes-or-less', 'time-to-make', 'course...   
1  ['30-minutes-or-less', 'time-to-make', 'course...   
2  ['time-to-make', 'course', 'preparation', 'mai...   
3  ['60-minutes-or-less', 'time-to-make', 'course...   
4  ['weeknight', 'time-to-make', 'course', 'main-...   

                                    nutrition  n_steps  \
0       [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
1   [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
2  [269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]        6   
3   [368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]       11   
4   [352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]        5   

                                               steps  \
0  ['make a choice and proceed with recipe', 'dep...   
1  ['preheat oven to 425 degrees f', 'press dough...   
2  ['brown ground beef in large pot', 'add choppe...   
3  ['place potatoes in a large pot of lightly sal...   
4  ['mix all ingredients& boil for 2 1 / 2 hours ...   

                                         description  \
0  autumn is my favorite time of year to cook! th...   
1  this recipe calls for the crust to be prebaked...   
2  this modified version of 'mom's' chili was a h...   
3  this is a super easy, great tasting, make ahea...   
4  my dh's amish mother raised him on this recipe...   

                                         ingredients  n_ingredients  
0  ['winter squash', 'mexican seasoning', 'mixed ...              7  
1  ['prepared pizza crust', 'sausage patty', 'egg...              6  
2  ['ground beef', 'yellow onions', 'diced tomato...             13  
3  ['spreadable cheese with garlic and herbs', 'n...             11  
4  ['tomato juice', 'apple cider vinegar', 'sugar...              8

In [ ]:
recipes.rename(columns = {'id':'recipe_id'}, inplace = True)

In [ ]:
df = pd.merge(ratings, recipes, on='recipe_id', how='inner')
# Take a look at the data
df.head()

user_id  recipe_id        date  rating      u      i  \
0     2046       4684  2000-02-25     5.0  22095  44367   
1    12882       4684  2002-03-13     5.0  10399  44367   
2    37758       4684  2002-06-17     5.0   4954  44367   
3    37636       4684  2003-05-08     5.0    831  44367   
4    54697       4684  2003-06-30     5.0   1147  44367   

                                   name  minutes  contributor_id   submitted  \
0  flank steak with lime chipotle sauce       75            1533  1999-11-18   
1  flank steak with lime chipotle sauce       75            1533  1999-11-18   
2  flank steak with lime chipotle sauce       75            1533  1999-11-18   
3  flank steak with lime chipotle sauce       75            1533  1999-11-18   
4  flank steak with lime chipotle sauce       75            1533  1999-11-18   

                                                tags  \
0  ['time-to-make', 'course', 'main-ingredient', ...   
1  ['time-to-make', 'course', 'main-ingredient', ...   
2  ['time-to-make', 'course', 'main-ingredient', ...   
3  ['time-to-make', 'course', 'main-ingredient', ...   
4  ['time-to-make', 'course', 'main-ingredient', ...   

                                      nutrition  n_steps  \
0  [487.8, 16.0, 283.0, 13.0, 52.0, 20.0, 26.0]        6   
1  [487.8, 16.0, 283.0, 13.0, 52.0, 20.0, 26.0]        6   
2  [487.8, 16.0, 283.0, 13.0, 52.0, 20.0, 26.0]        6   
3  [487.8, 16.0, 283.0, 13.0, 52.0, 20.0, 26.0]        6   
4  [487.8, 16.0, 283.0, 13.0, 52.0, 20.0, 26.0]        6   

                                               steps description  \
0  ['mix honey with chilies , mustard , lime juic...         yum   
1  ['mix honey with chilies , mustard , lime juic...         yum   
2  ['mix honey with chilies , mustard , lime juic...         yum   
3  ['mix honey with chilies , mustard , lime juic...         yum   
4  ['mix honey with chilies , mustard , lime juic...         yum   

                                         ingredients  n_ingredients  
0  ['flank steaks', 'honey', 'chipotle chiles in ...             10  
1  ['flank steaks', 'honey', 'chipotle chiles in ...             10  
2  ['flank steaks', 'honey', 'chipotle chiles in ...             10  
3  ['flank steaks', 'honey', 'chipotle chiles in ...             10  
4  ['flank steaks', 'honey', 'chipotle chiles in ...             10

In [ ]:
new_rating = df[['user_id','recipe_id','rating','name','n_steps']].sample(frac = 0.02)
n_users=new_rating.user_id.unique().shape[0]
n_items=new_rating.recipe_id.unique().shape[0]
print('Name of users='+str(n_users)+'| Number of recipes='+ str(n_items))
train_data=new_rating
train_data.head()

Name of users=5572| Number of recipes=11385


user_id  recipe_id  rating                                   name  \
107608    27381      45860     3.0             refrigerator sugar cookies   
191766   162826      63377     5.0                  nutty oven fried fish   
622350   953275     382136     5.0                       nine a day salad   
660889   655199     445890     5.0  kentucky kernel oven baked pork chops   
668517  1021800     134451     5.0                   hazelnut chip scones   

        n_steps  
107608       17  
191766        6  
622350        9  
660889        8  
668517       18

In [ ]:
# Create user-item matrix

matrix = new_rating.pivot_table(index='recipe_id', columns='user_id', values='rating')
matrix.head()

user_id    1533        1535        1634        1962        2178        \
recipe_id                                                               
62                NaN         NaN         NaN         NaN         NaN   
66                NaN         NaN         NaN         NaN         NaN   
167               NaN         NaN         NaN         NaN         NaN   
185               NaN         NaN         NaN         NaN         NaN   
186               NaN         NaN         NaN         NaN         NaN   

user_id    2310        2312        2586        3205        3288        ...  \
recipe_id                                                              ...   
62                NaN         NaN         NaN         NaN         NaN  ...   
66                NaN         NaN         NaN         NaN         NaN  ...   
167               NaN         NaN         NaN         NaN         NaN  ...   
185               NaN         NaN         NaN         NaN         NaN  ...   
186               NaN         NaN         NaN         NaN         NaN  ...   

user_id    2001436530  2001467287  2001497311  2001513060  2001836906  \
recipe_id                                                               
62                NaN         NaN         NaN         NaN         NaN   
66                NaN         NaN         NaN         NaN         NaN   
167               NaN         NaN         NaN         NaN         NaN   
185               NaN         NaN         NaN         NaN         NaN   
186               NaN         NaN         NaN         NaN         NaN   

user_id    2001898367  2001949873  2001987473  2002151809  2002312797  
recipe_id                                                              
62                NaN         NaN         NaN         NaN         NaN  
66                NaN         NaN         NaN         NaN         NaN  
167               NaN         NaN         NaN         NaN         NaN  
185               NaN         NaN         NaN         NaN         NaN  
186               NaN         NaN         NaN         NaN         NaN  

[5 rows x 5572 columns]

In [ ]:
# Normalize user-item matrix
matrix_norm = matrix.subtract(matrix.mean(axis=1), axis = 'rows').fillna(0)
matrix_norm.head()

user_id    1533        1535        1634        1962        2178        \
recipe_id                                                               
62                0.0         0.0         0.0         0.0         0.0   
66                0.0         0.0         0.0         0.0         0.0   
167               0.0         0.0         0.0         0.0         0.0   
185               0.0         0.0         0.0         0.0         0.0   
186               0.0         0.0         0.0         0.0         0.0   

user_id    2310        2312        2586        3205        3288        ...  \
recipe_id                                                              ...   
62                0.0         0.0         0.0         0.0         0.0  ...   
66                0.0         0.0         0.0         0.0         0.0  ...   
167               0.0         0.0         0.0         0.0         0.0  ...   
185               0.0         0.0         0.0         0.0         0.0  ...   
186               0.0         0.0         0.0         0.0         0.0  ...   

user_id    2001436530  2001467287  2001497311  2001513060  2001836906  \
recipe_id                                                               
62                0.0         0.0         0.0         0.0         0.0   
66                0.0         0.0         0.0         0.0         0.0   
167               0.0         0.0         0.0         0.0         0.0   
185               0.0         0.0         0.0         0.0         0.0   
186               0.0         0.0         0.0         0.0         0.0   

user_id    2001898367  2001949873  2001987473  2002151809  2002312797  
recipe_id                                                              
62                0.0         0.0         0.0         0.0         0.0  
66                0.0         0.0         0.0         0.0         0.0  
167               0.0         0.0         0.0         0.0         0.0  
185               0.0         0.0         0.0         0.0         0.0  
186               0.0         0.0         0.0         0.0         0.0  

[5 rows x 5572 columns]

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances

item_similarity=1-pairwise_distances(matrix_norm.T,metric='cosine')
print(item_similarity)
item_similarity=item_similarity.argsort()


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
def input_user(mv = 246):
    liked_recipes = []
    n=int(input('Enter the no. of recommendations you want:'))
    #mv=int(input('Enter the recipe id you liked :'))
    
    print('Recipes similar to the ones you liked:')
    mv=mv+1
          #header=['movie id','movie title','release date','video release date','IMDb URL','unknown','Action','Adventure','Animation',"Children's",'Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']
          #df2=pd.read_csv('u.item',sep='|',names=header,encoding='latin-1')
          #'''The movie titles are not present in the dataset u.data,it is being taken from another dataset by matching the movie ids'''
    rec_items=np.array((item_similarity[[mv],:n]))
    import matplotlib.pyplot as plt
    for mr in np.nditer(rec_items):
              #print(mr)
        for index,rows in df.iterrows():
              if(index==mr):
                  print(rows['name'])
                  print(rows['recipe_id'])
                  liked_recipes .append(rows['recipe_id']) 
                  
    return liked_recipes


In [ ]:
recipe_list = input_user()
while(True):

  ans = input("Do you want to update the recommendation list Y/N ?")
  if ans == 'Y':

    x = int(input("recipe you like from above "))
    if x in recipe_list:
        recipe_list.clear()
        recipe_list = input_user(mv = x)
    else:
        print("Not in a list")
  else:
    break

      


Enter the no. of recommendations you want:2
Recipes similar to the ones you liked:
flank steak with lime chipotle sauce
4684
hot fudge pudding cake ii
4332
Do you want to update the recommendation list Y/N ?Y
recipe you like from above 4332
Enter the no. of recommendations you want:3
Recipes similar to the ones you liked:
flank steak with lime chipotle sauce
4684
hot fudge pudding cake ii
4332
hot fudge pudding cake ii
4332
Do you want to update the recommendation list Y/N ?n
